# Generated by Django 3.2 on 2021-04-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='avaibility',
            new_name='available',
        ),
    ]
