# Generated by Django 3.2 on 2021-05-01 00:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
