# Generated by Django 3.2 on 2021-05-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_phone_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('-ratings__average', 'name')},
        ),
    ]
