# Generated by Django 3.2 on 2021-08-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('-available', '-ratings__average', 'name')},
        ),
    ]
