# Generated by Django 3.2 on 2021-04-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_address'),
        ('foods', '0002_auto_20210426_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtemplate',
            name='description',
        ),
        migrations.AddField(
            model_name='foodtemplate',
            name='image',
            field=models.ImageField(blank=True, upload_to='food/images'),
        ),
        migrations.AddField(
            model_name='foodtemplate',
            name='slug',
            field=models.SlugField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='food/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
