# Generated by Django 3.2 on 2021-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtemplate',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodtemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
