# Generated by Django 3.2 on 2021-05-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_options'),
        ('foods', '0006_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.restaurant'),
        ),
    ]
