# Generated by Django 3.2 on 2021-05-30 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_food_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
