# Generated by Django 3.2 on 2021-05-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_food_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-ratings__average', '-discount_percent', '-created')},
        ),
    ]
