# Generated by Django 3.2 on 2021-08-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_food_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-available', '-ratings__average', '-discount_percent', '-created')},
        ),
    ]
