# Generated by Django 3.2 on 2021-06-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='place',
            new_name='address',
        ),
    ]
