# Generated by Django 3.2 on 2021-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
