# Generated by Django 3.2 on 2021-04-26 09:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NE'),
        ),
    ]
