# Generated by Django 3.2 on 2021-07-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDeliveryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Register Delivery Users',
            },
        ),
        migrations.CreateModel(
            name='OrdersDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery_person.deliveryperson')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='delivery_person.deliveryperson')),
            ],
        ),
    ]
