# Generated by Django 3.2 on 2021-07-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0004_alter_deliveryperson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdesignation',
            name='completed',
        ),
    ]
