# Generated by Django 3.2 on 2021-07-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
