# Generated by Django 3.2 on 2021-08-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_delivery_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_chef',
        ),
    ]
