# Generated by Django 3.2 on 2021-04-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NE')),
                ('facebook_link', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='chef/logos')),
                ('description', models.TextField(blank=True)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
