# Generated by Django 3.2 on 2021-06-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_deliverylocation'),
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='location.deliverylocation'),
            preserve_default=False,
        ),
    ]
