# Generated by Django 3.2 on 2021-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(default='', max_length=250),
        ),
    ]
